language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - pip install tox-travis
script:
  - tox
before_deploy:
  - python setup.py bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: "GpgcFcui8c7soeVCEvoc147UNJ4wtebTsExaD2jzIEFWosTm86g8c+mDVsLO8Wd69q8qEqmQW5J8hTkk54zvJM/XkHdYFJ6tRBT+1lX97L6gsKiTt6Ft7tZFJeygECoJ/ELqFuYlA15BLNKZOwS6+ygp5jCm4To5nTXOBnCiM4aZSvZ5njEPOlex5AgzVRbO1rC04xt5C/On6zJfMvfNgkfWzTFVkcsaR08wvKcQ4GkEpwBSyBmlAgJ7PiW9H+8r4rpue0byk9Y8D3NPfWa8CUdsa7C0WBVmMKf0//5UmtdjXJoMhkxD6MH5pCWgGuNKg9lJd7C8Bgh0OmaRJxGFohWyAMV/C1hR3jzYh4sQE4MJT7Ef66NFzmxy+OEtT/k0bSC6bJ/K/I/9oXd3Tl9l8AZoRcdyx5YEmDv8jdVFWRAKup7qb02ZHUbCNkesBwSeNKRGosdwrl147BcQF9bPfVvsehY4K9/qCoEaWue29x8zu3sGPX2lMe6KMpSbJtPgwVW+Nz7pr1WQ80S2DCgto+S/5P2KZqculGj39yaFhlPExBjfIsNALrXuumfUPOCCj7e3FmUYK/vMPgFRXi+3wPIxEnf+WIqQlxbip8L4DFk9cipMjfBZW/6eS7YuA555Zci0Dka0kJOOV5q+mn7bQdj05K9jMd6EFHeeJrxFhI4="
  file: dist/mymath-*.whel
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    python: '3.6'
